// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKgfXJPvFpuM6tmZPr1d1-wpbkpgI-iGg',
    appId: '1:116165600653:web:b02c16793027059acf09c4',
    messagingSenderId: '116165600653',
    projectId: 'pkfolio-6b9c0',
    authDomain: 'pkfolio-6b9c0.firebaseapp.com',
    storageBucket: 'pkfolio-6b9c0.appspot.com',
    measurementId: 'G-PEYYKSDHBB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCZeNBOvIs6ONE2M2UjLcet_sI6N8kcm0',
    appId: '1:116165600653:ios:3fcf7b426d1d9695cf09c4',
    messagingSenderId: '116165600653',
    projectId: 'pkfolio-6b9c0',
    storageBucket: 'pkfolio-6b9c0.appspot.com',
    iosBundleId: 'com.example.pkFolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKgfXJPvFpuM6tmZPr1d1-wpbkpgI-iGg',
    appId: '1:116165600653:web:a623d95612f3435bcf09c4',
    messagingSenderId: '116165600653',
    projectId: 'pkfolio-6b9c0',
    authDomain: 'pkfolio-6b9c0.firebaseapp.com',
    storageBucket: 'pkfolio-6b9c0.appspot.com',
    measurementId: 'G-EVWHDJB232',
  );
}
